### ISSUE TITLE
Error on Nifi 2.0M2

### ISSUE THREAD

**Issue by oyeyemi** [MuseSystems/nifi_timestamp_resolution#1]
Hello sir,
I have followed all the procedure to install Nifi 2.0M2.
Then, i replaced my "flow.json.gz" with yours.
Then i started Nifi at https://localhost:8443/nifi
Unfortunately , Nifi started but did not give access to login.
I got the following error on the GUI:

**An unexpected error has occurred

{ "message":"Service Unavailable", "url":"https://localhost:8443/nifi-api/flow/current-user", "status":"503" }**

Please sir, can you download the json template of your flow for me to use.

Thank you sir.

**Comment by sbuttgereit** [comment]
Thank you for your report.

I've duplicated the error you're seeing in a fresh 2.0.0-M2 installation and, assuming that my duplication of the error is due to the same root cause that's causing the problem in your environment, I believe I know why you're getting that error.  The issue is that the there are still sensitive properties in the `flow.json.gz` that I published and your `nifi.properties` file doesn't have the right `nifi.sensitive.props.key` value to decrypt those properties.

I'll need to (at the very least) update the flow file published in this repository before you'll be able to make use of the `flow.json.gz` in the repo.   I'll try and find some time to do that over the next week or two.

**Comment by oyeyemi** [comment]
Alright sir.I would be very grateful for your kind effort.
Thank you so much.    On Wednesday, March 13, 2024 at 06:03:02 PM GMT+1, Steven C. Buttgereit ***@***.***> wrote:  
 
 


Thank you for your report.

I've duplicated the error you're seeing in a fresh 2.0.0-M2 installation and, assuming that my duplication of the error is due to the same root cause that's causing the problem in your environment, I believe I know why you're getting that error. The issue is that the there are still sensitive properties in the flow.json.gz that I published and your nifi.properties file doesn't have the right nifi.sensitive.props.key value to decrypt those properties.

I'll need to (at the very least) update the flow file published in this repository before you'll be able to make use of the flow.json.gz in the repo. I'll try and find some time to do that over the next week or two.
